-- BASE APP SCHEMA



-- User
CREATE TABLE "user"(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    username VARCHAR(32) NOT NULL UNIQUE,

    first_name VARCHAR(32) NOT NULL,

    last_name VARCHAR(32) NOT NULL,

    email VARCHAR(128) NOT NULL UNIQUE,

    phone_no VARCHAR(15) NOT NULL UNIQUE,

    CHECK (phone_no ~ `^\+?[0-9]{10,15}$`)




)




-- Organization


CREATE TABLE "organization"(

    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

    organization_name VARCHAR(128) NOT NULL,

    email VARCHAR(128) NOT NULL UNIQUE,


    phone_no VARCHAR(15) NOT NULL UNIQUE,

    CHECK (phone_no ~ `^\+?[0-9]{10,15}$`)

)


